<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Aset;
use App\Models\Transaksi;

class AsetSeeder extends Seeder
{
    public function run(): void
    {
        // Aset historis (perolehan sebelum periode berjalan) TIDAK ditautkan ke
        // transaksi — nilainya sudah tercatat di Jurnal Pembuka (JurnalLengkapSeeder).
        // Hanya pembelian aset SETELAH pembukaan yang berasal dari transaksi berjalan.
        // Ini meniru TransaksiService@simpanAsetDariTransaksi yang otomatis membuat
        // record Aset saat transaksi kategori "Pembelian Aset" disimpan.
        $trxLaptop = Transaksi::where('deskripsi', 'Pembelian Laptop & Printer Sekretariat')->first();

        // Tracker nomor urut per tahun untuk generate kode
        $noPerTahun = [];
        $kodeFor = function (string $tanggal) use (&$noPerTahun): string {
            $tahun = date('Y', strtotime($tanggal));
            $noPerTahun[$tahun] = ($noPerTahun[$tahun] ?? 0) + 1;
            return 'ASET-' . $tahun . '-' . str_pad($noPerTahun[$tahun], 3, '0', STR_PAD_LEFT);
        };

        $data = [
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Tanah Wakaf Masjid',
                'sumber_perolehan'         => 'Wakaf',
                'tanggal_perolehan'        => '2000-01-10',
                'nilai_tercatat'           => 800000000,
                'umur_manfaat'             => null,
                'tanggal_mulai_penyusutan' => null,
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Jl. Masjid Raya No. 1, Bandung',
                'nama_pemberi'             => 'H. Abdullah Bin Umar',
                'jumlah_unit'              => 1,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 800000000,
                'akumulasi_penyusutan'     => null,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Bangunan Masjid Utama',
                'sumber_perolehan'         => 'Wakaf',
                'tanggal_perolehan'        => '2002-05-15',
                'nilai_tercatat'           => 1200000000,
                'umur_manfaat'             => 50,
                'tanggal_mulai_penyusutan' => '2002-06-01',
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Jl. Masjid Raya No. 1, Bandung',
                'nama_pemberi'             => 'Panitia Pembangunan Masjid',
                'jumlah_unit'              => 1,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 696000000,
                'akumulasi_penyusutan'     => 504000000,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Gedung Madrasah / TPA',
                'sumber_perolehan'         => 'Infak Jamaah',
                'tanggal_perolehan'        => '2010-08-01',
                'nilai_tercatat'           => 350000000,
                'umur_manfaat'             => 30,
                'tanggal_mulai_penyusutan' => '2010-09-01',
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Jl. Masjid Raya No. 1, Bandung',
                'nama_pemberi'             => 'H. Rahmat Hidayat',
                'jumlah_unit'              => 1,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 210000000,
                'akumulasi_penyusutan'     => 140000000,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Rumah Imam / Marbot',
                'sumber_perolehan'         => 'Wakaf',
                'tanggal_perolehan'        => '2012-03-20',
                'nilai_tercatat'           => 200000000,
                'umur_manfaat'             => 30,
                'tanggal_mulai_penyusutan' => '2012-04-01',
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Jl. Masjid Raya No. 1A, Bandung',
                'nama_pemberi'             => 'Hj. Fatimah Azzahra',
                'jumlah_unit'              => 1,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 136000000,
                'akumulasi_penyusutan'     => 64000000,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Toilet & Tempat Wudhu',
                'sumber_perolehan'         => 'Infak Jamaah',
                'tanggal_perolehan'        => '2015-11-10',
                'nilai_tercatat'           => 80000000,
                'umur_manfaat'             => 20,
                'tanggal_mulai_penyusutan' => '2015-12-01',
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Samping Masjid Utama',
                'nama_pemberi'             => 'Panitia Renovasi Masjid',
                'jumlah_unit'              => 1,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 44000000,
                'akumulasi_penyusutan'     => 36000000,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Mimbar Khotbah Kayu Jati',
                'sumber_perolehan'         => 'Wakaf',
                'tanggal_perolehan'        => '2005-04-10',
                'nilai_tercatat'           => 15000000,
                'umur_manfaat'             => null,
                'tanggal_mulai_penyusutan' => null,
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Ruang Utama Masjid',
                'nama_pemberi'             => 'H. Syamsul Bachri',
                'jumlah_unit'              => 1,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 15000000,
                'akumulasi_penyusutan'     => null,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Karpet Sajadah Masjid',
                'sumber_perolehan'         => 'Wakaf',
                'tanggal_perolehan'        => '2020-03-01',
                'nilai_tercatat'           => 25000000,
                'umur_manfaat'             => 5,
                'tanggal_mulai_penyusutan' => '2020-04-01',
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Ruang Utama Masjid',
                'nama_pemberi'             => 'Hj. Siti Maryam',
                'jumlah_unit'              => 1,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 5000000,
                'akumulasi_penyusutan'     => 20000000,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Al-Quran (50 Eksemplar)',
                'sumber_perolehan'         => 'Donasi',
                'tanggal_perolehan'        => '2021-04-15',
                'nilai_tercatat'           => 5000000,
                'umur_manfaat'             => null,
                'tanggal_mulai_penyusutan' => null,
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Rak Al-Quran Masjid',
                'nama_pemberi'             => 'Komunitas Peduli Quran',
                'jumlah_unit'              => 50,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 5000000,
                'akumulasi_penyusutan'     => null,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Mukena (20 Set)',
                'sumber_perolehan'         => 'Donasi',
                'tanggal_perolehan'        => '2022-05-10',
                'nilai_tercatat'           => 3000000,
                'umur_manfaat'             => 3,
                'tanggal_mulai_penyusutan' => '2022-06-01',
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Ruang Wanita Masjid',
                'nama_pemberi'             => 'Ibu-Ibu Pengajian',
                'jumlah_unit'              => 20,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 1000000,
                'akumulasi_penyusutan'     => 2000000,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Sound System & Amplifier TOA',
                'sumber_perolehan'         => 'Pembelian',
                'tanggal_perolehan'        => '2019-06-20',
                'nilai_tercatat'           => 18000000,
                'umur_manfaat'             => 8,
                'tanggal_mulai_penyusutan' => '2019-07-01',
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Ruang Utama Masjid',
                'nama_pemberi'             => null,
                'jumlah_unit'              => 1,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 7000000,
                'akumulasi_penyusutan'     => 10000000,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Menara Speaker Adzan (4 Unit)',
                'sumber_perolehan'         => 'Wakaf',
                'tanggal_perolehan'        => '2018-01-05',
                'nilai_tercatat'           => 12000000,
                'umur_manfaat'             => null,
                'tanggal_mulai_penyusutan' => null,
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Menara Masjid',
                'nama_pemberi'             => 'H. Irfan Maulana',
                'jumlah_unit'              => 4,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 12000000,
                'akumulasi_penyusutan'     => null,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Jam Digital Jadwal Sholat',
                'sumber_perolehan'         => 'Pembelian',
                'tanggal_perolehan'        => '2021-01-10',
                'nilai_tercatat'           => 3500000,
                'umur_manfaat'             => 5,
                'tanggal_mulai_penyusutan' => '2021-02-01',
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Ruang Utama Masjid',
                'nama_pemberi'             => null,
                'jumlah_unit'              => 1,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 1750000,
                'akumulasi_penyusutan'     => 1750000,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'AC Split 2 PK (4 Unit)',
                'sumber_perolehan'         => 'Pembelian',
                'tanggal_perolehan'        => '2020-07-15',
                'nilai_tercatat'           => 28000000,
                'umur_manfaat'             => 8,
                'tanggal_mulai_penyusutan' => '2020-08-01',
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Ruang Utama Masjid',
                'nama_pemberi'             => null,
                'jumlah_unit'              => 4,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 14875000,
                'akumulasi_penyusutan'     => 13125000,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Kipas Angin Gantung (6 Unit)',
                'sumber_perolehan'         => 'Pembelian',
                'tanggal_perolehan'        => '2017-09-01',
                'nilai_tercatat'           => 4800000,
                'umur_manfaat'             => 5,
                'tanggal_mulai_penyusutan' => '2017-10-01',
                'kondisi_aset'             => 'RUSAK BERAT',
                'lokasi_aset'              => 'Gudang',
                'nama_pemberi'             => null,
                'jumlah_unit'              => 6,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'TIDAK AKTIF',
                'nilai_buku'               => 0,
                'akumulasi_penyusutan'     => 4800000,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Mobil Jenazah Toyota HiAce',
                'sumber_perolehan'         => 'Pembelian',
                'tanggal_perolehan'        => '2018-10-10',
                'nilai_tercatat'           => 280000000,
                'umur_manfaat'             => 10,
                'tanggal_mulai_penyusutan' => '2018-11-01',
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Garasi Masjid',
                'nama_pemberi'             => null,
                'jumlah_unit'              => 1,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 126000000,
                'akumulasi_penyusutan'     => 154000000,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Mesin Pompa Air',
                'sumber_perolehan'         => 'Pembelian',
                'tanggal_perolehan'        => '2019-03-12',
                'nilai_tercatat'           => 5000000,
                'umur_manfaat'             => 8,
                'tanggal_mulai_penyusutan' => '2019-04-01',
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Ruang Utilitas',
                'nama_pemberi'             => null,
                'jumlah_unit'              => 1,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 2406250,
                'akumulasi_penyusutan'     => 3093750,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'Generator Listrik 5000 Watt',
                'sumber_perolehan'         => 'Pembelian',
                'tanggal_perolehan'        => '2020-12-01',
                'nilai_tercatat'           => 12000000,
                'umur_manfaat'             => 8,
                'tanggal_mulai_penyusutan' => '2021-01-01',
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Ruang Utilitas',
                'nama_pemberi'             => null,
                'jumlah_unit'              => 1,
                'dokumen_pendukung'        => null,
                'keterangan'               => null,
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 6000000,
                'akumulasi_penyusutan'     => 5000000,
            ],
            [
                'transaksi_id'             => null,
                'nama_aset'                => 'CCTV System (8 Kamera)',
                'sumber_perolehan'         => 'Infak Jamaah',
                'tanggal_perolehan'        => '2024-12-01',
                'nilai_tercatat'           => 8500000,
                'umur_manfaat'             => null,
                'tanggal_mulai_penyusutan' => null,
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Belum dipasang',
                'nama_pemberi'             => 'Panitia Masjid',
                'jumlah_unit'              => 8,
                'dokumen_pendukung'        => null,
                'keterangan'               => 'Belum dipasang, masih dalam pengadaan',
                'status_aset'              => 'TIDAK AKTIF',
                'nilai_buku'               => 8500000,
                'akumulasi_penyusutan'     => 0,
            ],
            [
                'transaksi_id'             => $trxLaptop?->id,
                'nama_aset'                => 'Laptop & Printer Sekretariat',
                'sumber_perolehan'         => 'Pembelian',
                'tanggal_perolehan'        => '2026-05-10',
                'nilai_tercatat'           => 18000000,
                'umur_manfaat'             => 5,
                'tanggal_mulai_penyusutan' => '2026-06-01',
                'kondisi_aset'             => 'BAIK',
                'lokasi_aset'              => 'Ruang Sekretariat Masjid',
                'nama_pemberi'             => null,
                'jumlah_unit'              => 1,
                'dokumen_pendukung'        => null,
                'keterangan'               => 'Dibeli dari transaksi operasional 2026 (auto-generate aset)',
                'status_aset'              => 'AKTIF',
                'nilai_buku'               => 18000000,
                'akumulasi_penyusutan'     => 0,
            ],
        ];

        foreach ($data as $item) {
            $item['kode_aset'] = $kodeFor($item['tanggal_perolehan']);
            Aset::create($item);
        }
    }
}