name: deploy-to-azure

on:
  push:
    branches: [main, development]

env:
  ACR_NAME: acrkeuanganmasjid
  IMAGE: keuangan-masjid
  RESOURCE_GROUP: rg-keuangan-masjid

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login ke Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build & push image ke ACR
        run: |
          az acr build --registry $ACR_NAME --no-cache \
            --image $IMAGE:${{ github.sha }}  --image $IMAGE:latest .

  deploy-dev:
    needs: build
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Login ke Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy ke dev
        run: |
          az containerapp update \
            --name mosque-app-dev --resource-group $RESOURCE_GROUP \
            --image $ACR_NAME.azurecr.io/$IMAGE:${{ github.sha }}

  deploy-prod:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login ke Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy ke prod
        run: |
          az containerapp update \
            --name mosque-app --resource-group $RESOURCE_GROUP \
            --image $ACR_NAME.azurecr.io/$IMAGE:${{ github.sha }}
